//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumer
    {
        public Consumer()
        {
            this.Vacuum_cleaners = new HashSet<VacuumCleaner>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int countryId { get; set; }
    
        public virtual Country Countries { get; set; }
        public virtual ICollection<VacuumCleaner> Vacuum_cleaners { get; set; }
    }
}
