//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int id { get; set; }
        public int cleanerId { get; set; }
        public int userId { get; set; }
        public decimal price { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual User Users { get; set; }
        public virtual VacuumCleaner Vacuum_cleaners { get; set; }
    }
}
