//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public string pass { get; set; }
        public int type { get; set; }
        public int buyCount { get; set; }
        public decimal buySumm { get; set; }
        public string creditCard { get; set; }
    
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
